variable id_subnet_a {}
variable region {}
variable route53_zoneid{}
variable id_subnet_b {}
variable site {}
variable id_subnet_c {}
variable alb_security_groups {}
variable id_vpc_main {}
variable ec2_instance1 {}
variable ec2_instance2 {}
variable db_name {}
variable db_user {}
variable db_port {}
variable db_password {}
variable db_engine_version {}
variable db_engine {}
variable db_public_access {}
variable db_storage_size {}
variable db_storage_type {}
variable db_instance_class {}
variable db_multi_az {}
variable db_parameter_group_name {}
variable db_backup_retention_period {}
variable db_backup_window {}
variable db_maintenance_window {}
variable db_final_snapshot_identifier {}
variable db_vpc_security_group_ids {}
variable db_subnet_group_name {}
variable env {}
