variable id_subnet_a_dev {}
variable region {}
variable id_subnet_b_dev {}
variable id_subnet_c_dev {}
variable security_groups {}
variable id_vpc_main_dev {}
variable ec2_instance1 {}
variable ec2_instance2 {}
variable db_name {}
variable db_user {}
variable db_port {}
variable db_password {}
variable db_engine_version {}
variable db_engine {}
variable db_public_access {}
variable db_storage_size {}
variable db_storage_type {}
variable db_instance_class {}
variable db_multi_az {}
variable db_parameter_group_name {}
variable db_backup_retention_period {}
variable db_backup_window {}
variable db_maintenance_window {}
variable db_final_snapshot_identifier {}
variable db_vpc_security_group_ids {}
variable db_subnet_group_name {}
variable s3-policy {}
